sweet_market_place14/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sweet_market_place14_app.urls')),
]

sweet_market_place14_app/urls.py
from django.urls import path
from .views import home_view, upload_product, ProductListView, product_detail

app_name = 'sweet_market_place14_app'

urlpatterns = [
    path('', home_view, name='home'),
    path('upload_product/', upload_product, name='upload_product'),
    path('products/', ProductListView.as_view(), name='products'),
    path('product/<int:product_id>/', product_detail, name='product'),

]

account/models.py
from django.db import models

# Create your models here.

sweet_market_place14_app/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/', null=True)
    ingredients = models.TextField()
    weight_grams = models.PositiveIntegerField(default=0)
    available_quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

sweet_market_place14_app/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image', 'ingredients', 'weight_grams', 'available_quantity']

account/views.py
from django.shortcuts import render

# Create your views here.

sweet_market_place14_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm
from django.views.generic import ListView
from .models import Product


def home_view(request):
    return render(request, template_name='sweet_market_place14_app/home.html')


def upload_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = ProductForm()
    return render(request, 'sweet_market_place14_app/upload_product.html', {'form': form})


class ProductListView(ListView):
    model = Product
    template_name = 'sweet_market_place14_app/products.html'


def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['product'] = context['object_list']
    return context


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'sweet_market_place14_app/product.html', {'product': product})

sweet_market_place14_app/templates/sweet_market_place14_app/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>Produse de cofetarie</title>
    {% block page_class %}{% endblock %}
</head>
<body>
    {% include "sweet_market_place14_app/navbar.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

sweet_market_place14_app/templates/sweet_market_place14_app/carousel.html
{% load static %}
{% block carousel %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/carousel_1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carousel_2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carousel_3.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carousel_4.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carousel_5.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carousel_6.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>
{% endblock %}

sweet_market_place14_app/templates/sweet_market_place14_app/home.html
{% extends "sweet_market_place14_app/base.html" %}

{% block content %}
<div class="container spaced-top-5 black-bg">
    <div class="row">
        <div class="col">
            <div class="row">
                <h1 class="heading-title">Savoare delicata. Textura imaculata. Expresie unica.</h1>
            </div>
            <a href="{% url 'sweet_market_place14_app:upload_product' %}">
                <button class="btn-custom spaced-top-2">Incarca produse</button>
            </a>
        </div>
        <div class="col">
            {% include 'sweet_market_place14_app/carousel.html' %}
        </div>
    </div>
</div>
{% endblock %}

sweet_market_place14_app/templates/sweet_market_place14_app/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid container">
    <a class="navbar-brand brand-logo" href="/">Pyta 14</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
          <a class="nav-link active" aria-current="page" href="{% url 'sweet_market_place14_app:products' %}">Products</a>
          {% if user.is_authenticated %}
            <a class="nav-link" href="#" title="Deautentificare"> #
              <i class="fas fa-user"></i>
            </a>
            <form class="nav-link" action="#" method="POST">
              {% csrf_token %}
              <button class="logout-button" type="submit">
                <i class="fas fa-sign-out-alt"></i>
              </button>
            </form>
            <a class="nav-link" href="#" title="Coșul tău">
              <i class="fa-solid fa-shopping-cart"></i>
            </a>
          {% else %}
            <a class="nav-link" href="#" title="Autentificare">
              <i class="fa-solid fa-sign-in-alt"></i>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>
{% endblock %}

sweet_market_place14_app/templates/sweet_market_place14_app/product.html
{% extends "sweet_market_place14_app/base.html" %}
{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="col">
            <img src="{{ product.image.url }}" alt="{{ product.name }} Image" class="img-fluid">
        </div>
        <div class="col">
            <div class="row">
                <h5 class="card-title">{{ product.name }} | <span class="text-success">Available: {{product.available_quantity}}</span></h5>
                <h5 class="card-title text-danger">Price: {{ product.price }} RON</h5>
                <p class="card-text"><p> {{product.description}}</p>
                <p class="card-text"><p>Ingredients: {{product.ingredients}}</p>
                <p class="card-text"><small class="text-muted">Weight: {{ product.weight_grams }} g</small></p>
            </div>
            {% if user.is_authenticated  %}
                <a href="#">
                    <button class="btn-custom-reverse spaced-top-2">Add to cart</button>
                </a>
            {% endif %}
        </div></br>
    </div>
</div>
{% endblock %}

sweet_market_place14_app/templates/sweet_market_place14_app/products.html
{% extends "sweet_market_place14_app/base.html" %}
{% block content %}
    <div class="container">
        <h2 style="text-align: center;
            font-size: 70px;
            font-weight: 700;
            text-transform: none;
            font-style: normal;
            text-decoration: none;
            line-height: 1em;
            letter-spacing: -3px;
            margin-top: 50px;
            margin-bottom: 50px;">Products
        </h2>
        <div class="row">
            {% for product in product_list %}
                <div class="col-6 my-4">
                    <div class="card">
                        <img src="{{ product.image.url }}" alt="{{ product.name }} Image">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">Price: {{ product.price }} RON</p>
                        <a href="/product/{{ product.id }}">
                            <button class="btn-custom spaced-top-2">See details</button>
                        </a>
                        {% if user.is_authenticated %}
                            <a href="#">
                                <button class="btn-custom-reverse spaced-top-2">Add to cart</button>
                            </a>
                        {% endif %}
                    </div>
                </div>

                {% if forloop.counter|divisibleby:2 and not forloop.last %}
                    </div></div><div class="container"><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

sweet_market_place14_app/templates/sweet_market_place14_app/upload_product.html
<!DOCTYPE html>
<html>
<head>

    <title>Incarcati un produs</title>

</head>
<body>
    <h1>Incarca un produs</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Incarca produsul">
    </form>
</body>
</html>